//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGo3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdherentCotisation
    {
        public string codeCotisation { get; set; }
        public string codeAdherent { get; set; }
        public Nullable<System.DateTime> datePaiementCotisation { get; set; }
    
        public virtual Adherent Adherent { get; set; }
        public virtual Cotisation Cotisation { get; set; }
    }
}
