//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGo3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campagne
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Campagne()
        {
            this.Dons = new HashSet<Don>();
            this.Projets = new HashSet<Projet>();
        }
    
        public string codeCampagne { get; set; }
        public Nullable<System.DateTime> dateDebutCampagne { get; set; }
        public Nullable<System.DateTime> dateFinCampagne { get; set; }
        public Nullable<decimal> montantCibleCampagne { get; set; }
        public Nullable<decimal> totalRealiseCampagne { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Don> Dons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projet> Projets { get; set; }
    }
}
