//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGo3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompteRendu
    {
        public string codeCompteRendu { get; set; }
        public Nullable<System.DateTime> dateCompteRendu { get; set; }
        public string realisationCompteRendu { get; set; }
        public Nullable<System.DateTime> dateFinEstimeeProjetCompteRendu { get; set; }
        public string echeancierProjetCompteRendu { get; set; }
        public Nullable<decimal> totalFondsCollectesCompteRendu { get; set; }
        public Nullable<decimal> totalDepensesCompteRendu { get; set; }
        public string etatAvancementProjetCompteRendu { get; set; }
        public string etatRisquesProjetCompteRendu { get; set; }
        public string frequenceCompteRendu { get; set; }
        public string codeProjetCompteRendu { get; set; }
        public string codeAdherentCompteRendu { get; set; }
    
        public virtual Adherent Adherent { get; set; }
        public virtual Projet Projet { get; set; }
    }
}
