//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGo3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Don
    {
        public string codeDon { get; set; }
        public Nullable<System.DateTime> dateDon { get; set; }
        public Nullable<decimal> montantDon { get; set; }
        public string typePaiementDon { get; set; }
        public string codeDonateurDon { get; set; }
        public string codeCampagneDon { get; set; }
    
        public virtual Campagne Campagne { get; set; }
        public virtual Donateur Donateur { get; set; }
    }
}
