//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGo3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projet()
        {
            this.CompteRendus = new HashSet<CompteRendu>();
            this.Campagnes = new HashSet<Campagne>();
        }
    
        public string codeProjet { get; set; }
        public string titreProjet { get; set; }
        public string descriptionProjet { get; set; }
        public string sommaireProjet { get; set; }
        public string statutProjet { get; set; }
        public Nullable<System.DateTime> dateDebutEstimeeProjet { get; set; }
        public Nullable<System.DateTime> dateFinEstimeeProjet { get; set; }
        public string echeancierProjet { get; set; }
        public Nullable<decimal> budgetProjet { get; set; }
        public Nullable<decimal> totalFondsCollectesProjet { get; set; }
        public Nullable<decimal> totalDepensesProjet { get; set; }
        public Nullable<System.DateTime> dateDebutRelleProjet { get; set; }
        public Nullable<System.DateTime> dateFinRelleProjet { get; set; }
        public string realisationCompleteesProjet { get; set; }
        public string risquesProjet { get; set; }
        public string etatAvancementProjet { get; set; }
        public string codeAdherentProposeProjet { get; set; }
        public string codeAdherentCoopteProjet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompteRendu> CompteRendus { get; set; }
        public virtual Equipe Equipe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Campagne> Campagnes { get; set; }
    }
}
